### ISSUE TITLE
在所有BaseViewController中如何使用哩。

### ISSUE THREAD

**Issue by jinxiansen** [Soul-Beats/UINavigationController-SLTransitioning#1]
如题，想测试left效果，不知如何基于基类中调用。

**Comment by Soul-Beats** [comment]
首先，这是一个UINavigationController的委托，所以，如果你不想创建一个导航控制器的子类的话，在你导航控制器的rootViewController的viewDidLoad方法中调用
`self.navigationController.transitioningStyle = SLNavigationTransitioningStyleResignLeft;`
方法，之后的push和pop都是这种动画了。 
可以参考Demo。

**Comment by Soul-Beats** [comment]
这个动画是通过UINavigationController来控制的，而不是UIViewController，UIViewController只是通过一个属性来自定义间接控制导航动画，本质都是通过UINavigationController来控制。

**Comment by jinxiansen** [comment]
尝试了，但是在push或pop回来的时候，导航栏下边会有白条，感觉不是很美观。您可以下个猫眼电影看看，我是想要这样的效果的。

**Comment by Soul-Beats** [comment]
额。我在Demo里面看的话没有白条哦。 不是很清楚你的效果。 
猫眼的那个挺复杂的，不是用这种技术的，是禁掉了系统的返回，添加了自定义的手势，然后拿取之前存储的snapshot，做的动画。

**Comment by jinxiansen** [comment]
留个QQ交流交流呗。
